### ISSUE TITLE
"msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc635758530>"

### ISSUE THREAD

**Issue by ikunduraci** [deekayen/ansible-role-win_updates#2]
When trying to return only the title of the updates available to a machine, the output returns an error;

`TASK [print all the updates] *********************************************************************************************
ok: [host1] => (item=dcf40467-26c9-4df1-a5f5-38f0a769ca7a) => {
    "item": "dcf40467-26c9-4df1-a5f5-38f0a769ca7a",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc635758530>"
}
ok: [host1] => (item=88702acd-f1cb-4e17-b5f6-02f0b3d45823) => {
    "item": "88702acd-f1cb-4e17-b5f6-02f0b3d45823",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc635758590>"
}
ok: [host1] => (item=96d37c57-ed41-4e71-9e56-4f44352ce5e3) => {
    "item": "96d37c57-ed41-4e71-9e56-4f44352ce5e3",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc6357585f0>"
}
ok: [host1] => (item=749e3c7a-4779-4c14-bccd-2b608c39ddc9) => {
    "item": "749e3c7a-4779-4c14-bccd-2b608c39ddc9",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc635758650>"
}
ok: [host1] => (item=adf937ce-7b6d-49de-a9ea-96f20413274a) => {
    "item": "adf937ce-7b6d-49de-a9ea-96f20413274a",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc6357586b0>"
}
ok: [host1] => (item=8832eabb-68ee-4ef9-b45e-b8fee94581b8) => {
    "item": "8832eabb-68ee-4ef9-b45e-b8fee94581b8",
    "msg": "<built-in method title of AnsibleUnsafeText object at 0x7fc635758710>"
}`

Playbook below - 
`---
- hosts: all
  gather_facts: no
  vars:
    win_update_categories:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
        - UpdateRollups
  tasks:
    - block:
        - name: Checking for Available Windows Updates
          win_updates:
            category_names: "{{ win_update_categories }}"
            state: searched
          register: available_updates
        - name: print all the updates
          debug: msg={{ item.title }}
          with_items: "{{ available_updates.updates }}"`

Ansible + Python version -
`ansible 2.4.0.0
  config file = /home/admin/ansible/windows/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]`

Windows Host -
Server 2012 R2

**Comment by grantmatheny** [comment]
@ikunduraci what was the fix that caused you to close this? I'm still experiencing it in Ansible 2.9.x and wondered if it was just a syntax change.

**Comment by ikunduraci** [comment]
@grantmatheny  going back a while now :) but check out my repo for the playbook i ended up building (https://github.com/ikunduraci/Ansible/blob/master/Windows/check-updates/check-updates.yml).. hope this helps!

**Comment by grantmatheny** [comment]
@ikunduraci that helped a ton! Thanks!

**Comment by RakeshSindhu** [comment]
@ikunduraci  i am getting below error 

{"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'iteritems'. 'dict object' has no attribute 'iteritems'\n\nThe error appears to be in '/runner/project/Window_Update.yml': line 31, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    - block:\n        - debug:\n          ^ here\n"}
